language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install . coveralls"
# command to run tests
script:
  coverage run --source=nltk_tgrep setup.py test
after_success:
  coveralls

